### ISSUE TITLE
offers.setup 

### ISSUE THREAD

**Issue by scyllaelemental** [Alex7Kom/node-steam-tradeoffers#132]
@srabouin i used your getAPIKey(); fuction and 
```javascript
client.on('webSessionID', function(sessionID) {
client.webLogOn(function(cookies) {
        offers.setup({"sessionID": sessionID, "webCookie": cookies}, function() { offers.getAPIKey(); logger.info('API KEY: '+offers.getAPIKey()); });});});
```
this 
```javascript

C:\Users\Scylla\Desktop\CrateDump>node ornek.js
info: Logged on to Steam
info: API KEY: undefined
```

how i can handle with that issue?

**Comment by LeCoffee** [comment]
Your code returns an undefined API key because the getAPIKey function was not intended to be used this way. 

NodeJS is written asynchronously which means functions don't usually "return" things instead you pass a callback to them and it will be called when the data is ready.

To fix your code you will need to make your code asynchronous e.g: 

```
client.on('webSessionID', function(sessionID) {
    client.webLogOn(function(cookies) {
        offers.setup(
        {
             "sessionID": sessionID, 
            "webCookie": cookies
        }, function() { 
            offers.getAPIKey( function (apiKey) {
                logger.info('API KEY: '+ apiKey); 
            });
        });
    });
});

```

Note the above was written in this box and hasn't actually been tested.
On a side note I advise you read some more documentation on NodeJS to better understand the asynchronous side of NodeJS
