### ISSUE TITLE
Unhandled 'error' event - Error: Disconnected.

### ISSUE THREAD

**Issue by metheyes** [Alex7Kom/node-steam-tradeoffers#157]
For some reason I'm getting:
![ss 2015-09-20 at 01 39 44](https://cloud.githubusercontent.com/assets/14365634/9978591/62f5928a-5f30-11e5-9ed2-0f7d052a8d5c.png)

I've tried my "own version", and the donation_bot.js, as well as offerbot.js. I'm getting the same problem on every script.
It doesn't even matter if I put in false log-in credentials, it seem to disconnect me anyways when I'm starting it up.
Perhaps I don't get connected to the Steam servers or something?

**Comment by andrewda** [comment]
This is the expected behavior. This also isn't an issue (period) with node-steam-tradeoffers. Just for future reference, post this on the node-steam-forum or /r/SteamBot to get more help.

To fix your problem, though, you have to enter your correct login information making sure that the `authCode` variable is an empty string. Run the bot once and this error will appear again. Now check the email associated with your bot's account and paste the Steam Guard code sent to you by Steam into the `authCode` variable. Now running the bot should work flawlessly.

**Comment by metheyes** [comment]
I thought it was an issue. Anyways, I used to use steam-tradeoffers, (before steamclient, steamuser, steamfriends, steamweblogon etc was added for each specific thing) and it worked flawlessly.

I have my old sentry file and my authCode variable is empty. (= '')
I also tried removing my sentry file and it did not help.

**Comment by andrewda** [comment]
We'll continue this [here](https://github.com/steam-forward/node-steam-forum/issues) or [here](http://reddit.com/r/SteamBot)

**Comment by metheyes** [comment]
Opened up an issue there, thanks and sorry.
