### ISSUE TITLE
is makeOffer's amount propertie working?

### ISSUE THREAD

**Issue by MatijsVDG** [Alex7Kom/node-steam-tradeoffers#272]
First of all thanks for this library, it makes trading with bots very easy!

Im having a little struggle here, for some reason using **amount: 2** (anything else but 1) is not working.

Putting this into the **itemsFromThem** array, will cause that "error (26)"

`[ { appid: 730, contextid: 2, amount: 2, assetid: '6480995034' } ]`

but putting this (with all amounts set to 1):
`[ { appid: 730, contextid: 2, amount: 1, assetid: '6480995034' } ]`

it will not give that error and make the trade.

I have those items in my inventory so getting 2 items should work.

Sorry for my bad english, but anyone knows if **amount** is working fine or not? Or someone could tell me what im doing wrong?

Thanks in advance!
Matijs

**Comment by Exokay88** [comment]
Yo dude,
you are not supposed to use amount: 2 since a CS item is only 1 item. The CS Item's depend on the assetid.
At some games where you have an item like  
http://steamcommunity.com/id/Exokay88/inventory/#99900_6122170_84549264 (spiral knight item)
this one has a inner Amount. 
At these items you could use amount:2
But on CS you don't have stackable items.

**Comment by Exokay88** [comment]
and btw error 26 = Revoked
https://github.com/SteamRE/SteamKit/blob/master/Resources/SteamLanguage/eresult.steamd#L11

**Comment by MatijsVDG** [comment]
Ah fuck me.

Thanks alot for the answer. I have been messing around with this shit for like 2 days (not full days but you know what I mean xD)

Also that page I'm gonna bookmark.

Thanks again!

**Comment by Exokay88** [comment]
if you need help feel free to add me i can help ya pretty sure.

**Comment by Alex7Kom** [comment]
#121
