### ISSUE TITLE
error 15 (access denied) when making offers to certain users

### ISSUE THREAD

**Issue by buddhapest** [Alex7Kom/node-steam-tradeoffers#41]
is anyone seeing the following error when making offers?

`Error: There was an error sending your trade offer.  Please try again later. (15)`

it's only happening to a small % of users, but it's consistent for those users.  i'm at a bit of a loss of what might be causing it.

**Comment by LucasCroftLv** [comment]
I have this problem and it was exactly after I had made another trade, and plus when the trade was open all the possessions that i'd just traded were still there?

**Comment by dway** [comment]
same problem
{ [Error: There was an error sending your trade offer.  Please try again later. (15)] eresult: 15 }

**Comment by cymruu** [comment]
error 15 occurs when you trade with account that doesnt have space in inventory

**Comment by david500834** [comment]
hello guys,I have the same problem,but I'm sure that the relactionship between both me and my partner is friend .I can even make a trade offer by my hand ,so is there anything other problem with my program?

**Comment by DrBomb** [comment]
I am not using the library, but I had troubles with error 15 as well.
The trade token was sent as an array, on the form ['XXXXXX'], as soon as I fixed it it worked.

The odd thing was that with or without token if the user was my steam friend, the trade offer would not fail, I'd guess because if we are friends the token is unnecessary.

**Comment by lucenaxd** [comment]
For Future Visitors =)
Source: [Steam Error 15](https://steamerrors.com/15)

## 15 AccessDenied

**VALVE'S COMMENTS**
access is denied
**TRADE OFFERS**
You may receive this result when sending, accepting, declining, or canceling a trade offer. Below is an explanation of what this result means in this context.

You can't send or accept this trade offer because either you can't trade with the other user, or one of the parties in this trade can't send/receive one of the items in the trade. Possible causes: a) You aren't friends with the other user and you didn't provide a trade token. b) The trade token was wrong. c) You are trying to send or receive an item for a game in which you or the other user can't trade (e.g. due to a VAC ban). d) You are trying to send an item and the other user's inventory is full for that game.

**Comment by buddhapest** [comment]
i find that the primary cause is almost always
> d) You are trying to send an item and the other user's inventory is full for that game.

**Comment by MrBatman17** [comment]
I have the same problem. I want to trade from my account to another (both are mine) I have vac ban on both account BUT NOT in the game that i want to trade(tf2). With one of the accounts i can trade fine instantly and with my other account i can't even trade or contact steam support.Please help me it will be helpful.  
![capture](https://user-images.githubusercontent.com/33667163/32796100-628eefbe-c976-11e7-9c07-bc785c01fd6c.PNG)
![capture29](https://user-images.githubusercontent.com/33667163/32796104-66c27dd0-c976-11e7-82c0-94756bd923e7.PNG)

**Comment by DotkaProDotka** [comment]
MrBatman17 I got same things with you , steam support help you ? Or tell you for what you got this block ???
