### ISSUE TITLE
Item Name

### ISSUE THREAD

**Issue by Max0nyM** [Alex7Kom/node-steam-tradeoffers#92]
Hi Guys Help me please. How can i find item name in trade process ? + price of item.

**Comment by pmk010** [comment]
You should really at least attempt the problem yourself, especially since this is rather simple. I won't give you any code but I'll explain how to do it.

From the trade offer you take the asset id, load the partner's inventory and compare each assetid to the ids in the inventory. Once you find a match you take the index and can then find all the item information.

Depending on what exactly you want it will be the name or the market_name property.

**Comment by Max0nyM** [comment]
thx man, i already make it))

**Comment by Yashko** [comment]
@Max0nyM hi, can you give me your solucion please?

**Comment by srabouin** [comment]
https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService#GetTradeOffers_.28v1.29

Try adding get_descriptions to your getOffers call -- haven't used that but it seems like a good option

**Comment by Yashko** [comment]
Url for getting price of item:
http://steamcommunity.com/market/priceoverview/?currency=1&appid=730&market_hash_name=ITEM_NAME
Dont forget to encode url
