### ISSUE TITLE
a little help please?

### ISSUE THREAD

**Issue by mikelsx** [Alex7Kom/node-steam-tradeoffers#97]
How do i check if 
1. the items received in the trade offer are only CS:GO items ?
2. the user didnt request any item from the bot's inventory?

**Comment by mikelsx** [comment]
Bump, still looking for some help!

**Comment by Alex7Kom** [comment]
There is no point in bumping issues, since everyone who subscribed to the repo gets an email notification about each issue anyway. Next time 'bumping' happens I'll lock the issue immediately. Nobody here is obligated to help you.
Personally I think both of your problems are too easy, so do yourself a favour and solve them by yourself. At least show some effort by doing some code and if it doesn't work post it here. Nobody here is willing to code for you.
You are welcome.

**Comment by mikelsx** [comment]
`if(!offer.items_to_give){`
                  `   offers.acceptOffer({tradeOfferId: offer.tradeofferid});`
					`logger.info("A Trade has been accepted: " + offer.steamid_other);`
					    `for (i = 0; i < items_to_get.length; i++){`
                       ` logger.info("Items received: " + items[i]["assetid"]);`
                 `   }`
              `  }else {`
                  `   offers.declineOffer({tradeOfferId: offer.tradeofferid});`
					`logger.info("A Trade has been declined: " + offer.steamid_other);`
             `   }`

tried that, but it doesnt work

**Comment by pmk010** [comment]
The way to check if they are from are CSGO items is to take the partner's CSGO inventory and cross check the assetid with each item in it. If it appears, it's a CSGO item, otherwise it's not. As for checking if the user asked for any items from the bot just check items_to_give.

On a side note, it seems like you have very little idea what you are doing, considering you are having to ask such basic questions that you should be able to figure out on your own. You should perhaps try to learn the basics of javascript/node.js before attempting this and then take time to read through the documentation for this module as well as this https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService.

**Comment by RakouskyS** [comment]
For checking if the item is from CS:GO:

I would use a foreach loop and check if the "appid" (game specific) is the same as CS:GO's.

Good Luck
